name: Deploy Migrations to Production

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-22.04

        env:
            SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
            SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
            PRODUCTION_PROJECT_ID: cxzgcaupdpqtkduvhqcj
            OAUTH_GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
            OAUTH_GITHUB_SECRET: ${{ secrets.OAUTH_GITHUB_SECRET }}
            OAUTH_GOOGLE_CLIENT_ID: ${{ secrets.OAUTH_GOOGLE_CLIENT_ID }}
            OAUTH_GOOGLE_SECRET: ${{ secrets.OAUTH_GOOGLE_SECRET }}

        steps:
            - uses: actions/checkout@v3

            - uses: supabase/setup-cli@v1
              with:
                  version: latest

            - run: |
                  supabase link --project-ref $PRODUCTION_PROJECT_ID
                  supabase db push
            - run: supabase functions deploy flight-lookup --project-ref $PRODUCTION_PROJECT_ID --legacy-bundle
            - run: supabase functions deploy schedule-flight --project-ref $PRODUCTION_PROJECT_ID --legacy-bundle
